{% set version = "0.6.3" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: af24c2c298e26b0e7bca438838894219e466aeeec5cb8fab7cbad8444cddee32

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas >=0.23
    - shapely
    - fiona
    - pyproj
    - rtree

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: 'LICENSE.txt'
  summary: 'Geographic pandas extensions'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
