{% set version = "0.6.1" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: b72b8a870d55b30836cb4bea9e1b58b8317c008bcff8c86738f7ee5a69042b54

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pandas
    - shapely
    - fiona
    - pyproj
    - rtree

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: 'LICENSE.txt'
  summary: 'Geographic pandas extensions'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
