{% set version = "1.0.0rc1" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: b5308067dc92c0762931dc2c1d7f9be1e33f78def5af3865a263a0d2c1eca09d

build:
  number: 0
  noarch: python

outputs:
  - name: geopandas-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python >=3.9
        - pip
      run:
        - python >=3.9
        - numpy >= 1.22
        - pandas >=1.4.0
        - shapely >=2.0.0
        - packaging

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python >=3.9
      run:
        - python >=3.9
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - pyproj >=3.3.0
        - pyogrio >=0.7.2
        - matplotlib-base
        - mapclassify >=2.4.0
        - folium
        - xyzservices

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
    - martinfleis
