{% set version = "0.8.0" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: e954dd2b5c1f694845f3c2e604c692a78a27aab74fc9297e8d119ace11f903dd

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - pandas >=0.23
    - shapely
    - fiona
    - pyproj >=2.2.0
    - rtree

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: 'LICENSE.txt'
  summary: 'Geographic pandas extensions'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
