{% set version = "1.0.0.dev" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/archive/v{{ version }}.tar.gz
  sha256: 8c4cf4eba18291ea84170c7321bcf2b1ce98361e4cc0ae0d9c6b8b25b9dc70dc

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt --with-cython

requirements:
  build:
    - python
    - setuptools
    - cython
  run:
    - python
    - pandas
    - pyproj
    - shapely
    - fiona
    - six
    - rtree
    - descartes
    - matplotlib
    - psycopg2
    - sqlalchemy
    - pysal

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data/test.cpg
    - test_data/test.dbf
    - test_data/test.shp
    - test_data/test.shx

about:
  home: http://geopandas.org
  license: BSD 3-clause
  summary: 'Geographic pandas extensions.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
