{% set version = "0.9.0" %}

package:
  name: geopandas-suite
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 63972ab4dc44c4029f340600dcb83264eb8132dd22b104da0b654bef7f42630a

build:
  noarch: python
  number: 1
  noarch: python

outputs:
  - name: geopandas-base
    script: {{ PYTHON }} -m pip install . --no-deps -vv

    requirements:
      host:
        - python >=3.6
        - pip
      run:
        - python >=3.6
        - pandas >=0.24
        - shapely
        - pyproj >=2.2.0

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python >=3.6
      run:
        - python >=3.6
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - fiona
        - rtree
        - matplotlib-base

    test:
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
