{% set version = "1.0.0.dev" %}

package:
  name: geopandas
  version: {{ version }}

source:
  git_url: https://github.com/geopandas/geopandas.git
  git_branch: geopandas-cython
  patches:
    - geos_header.patch

build:
  number: 0
  script: 
    - set GEOS_HEADERS=%CONDA_PREFIX%\\include  # [win]
    - set GEOS_LIB=%CONDA_PREFIX%\\lib  # [win]
    - python setup.py install --single-version-externally-managed --record record.txt --with-cython

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - shapely
  run:
    - python
    - pandas
    - pyproj
    - shapely
    - fiona
    - six
    - rtree
    - descartes
    - matplotlib
    - psycopg2
    - sqlalchemy
    - pysal

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data/test.cpg
    - test_data/test.dbf
    - test_data/test.shp
    - test_data/test.shx

about:
  home: http://geopandas.org
  license: BSD 3-clause
  summary: 'Geographic pandas extensions.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
