{% set version = "0.2" %}

package:
    name: geopandas
    version: {{ version }}

source:
    fn: geopandas-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/g/geopandas/geopandas-{{ version }}.tar.gz
    md5: 47061076aa5e385b4ed773872397c86d

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - cython
    run:
        - python
        - pandas
        - pyproj
        - shapely
        - fiona
        - gdal 1.11.4
        - six
        - rtree
        - descartes
        - matplotlib
        - psycopg2  # [not win]
        - sqlalchemy
        - geopy ==1.10.0
        - pysal

test:
    imports:
        - geopandas
        - geopandas.io
    files:
        - test.cpg
        - test.dbf
        - test.shp
        - test.shx

about:
    home: http://geopandas.org
    license: BSD-3-clause
    summary: Geographic pandas extensions

extra:
    recipe-maintainers:
        - ocefpaf
        - jorisvandenbossche
