{% set version = "1.1.1" %}
{% set python_min = "3.10" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: 1745713f64d095c43e72e08e753dbd271678254b24f2e01db8cdb8debe1d293d

build:
  number: 0
  noarch: python

outputs:
  - name: geopandas-base
    script: build_base.sh
    build:
      noarch: python
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python {{ python_min }}
        - setuptools
        - pip
      run:
        - python >={{ python_min }}
        - numpy >=1.24
        - pandas >=2.0.0
        - shapely >=2.0.0
        - packaging

    test:
      requires:
        - python {{ python_min }}
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

  - name: geopandas
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('geopandas-base', exact=True) }}
        - pyproj >=3.5.0
        - pyogrio >=0.7.2
        - matplotlib-base
        - mapclassify >=2.5.0
        - folium
        - xyzservices

    test:
      requires:
        - python {{ python_min }}
      imports:
        - geopandas
        - geopandas.io
      files:
        - test_data

about:
  home: http://geopandas.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Geographic pandas extensions

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
    - martinfleis
