{% set version = "1.0.0.dev" %}

package:
  name: geopandas
  version: {{ version }}

source:
  git_url: https://github.com/geopandas/geopandas.git
  git_branch: geopandas-cython

build:
  number: 1
  skip: True  # [win and py<35]
  script:
    - python setup.py install --single-version-externally-managed --record record.txt --with-cython  # [not win]

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy 1.8.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - shapely
  run:
    - python
    - numpy >=1.8  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11  # [win and py36]
    - pandas
    - pyproj
    - shapely
    - fiona
    - six
    - rtree
    - descartes
    - matplotlib
    - psycopg2
    - sqlalchemy
    - pysal

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data/test.cpg
    - test_data/test.dbf
    - test_data/test.shp
    - test_data/test.shx

about:
  home: http://geopandas.org
  license: BSD 3-clause
  summary: 'Geographic pandas extensions.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
