{% set version = "0.3.0" %}

package:
  name: geopandas
  version: {{ version }}

source:
  url: https://github.com/geopandas/geopandas/releases/download/v{{ version }}/geopandas-{{ version }}.tar.gz
  sha256: e63bb32a3e516d8c9bcd149c22335575defdc5896c8bdf15c836608f152a920b

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas
    - pyproj
    - shapely
    - fiona
    - six
    - rtree
    - descartes
    - matplotlib
    - psycopg2
    - sqlalchemy
    - pysal

test:
  imports:
    - geopandas
    - geopandas.io
  files:
    - test_data
    - test_issue_31

about:
  home: http://geopandas.org
  license: BSD 3-clause
  summary: 'Geographic pandas extensions.'

extra:
  recipe-maintainers:
    - ocefpaf
    - jorisvandenbossche
    - jdmcbr
