travis:
  secure:
    BINSTAR_TOKEN: yKdCZmSL7gctNCWee0xz58Po12r6jwXL1McR5pyHD56fHm5zaw/X8n8Alq1TGaF/GIu9NKhh6aaPPKskPbs7JBts1gRR/yJwaCrlAcLU/UWAnV0cv2x+HXMu23zcd8fOrV9Lk5YDnIh3RkYI95NM+yptmr0jZ/0C8PH7JOxfqhoyFjGX3b0JdtUJLWpp05DXizZvwGOqWNd2ycKgVBlRIYIpa4lo8TPA6ngBLXS2yf0a6vJnaU+DTtbewz9wDRxSIhGZ7NAynyDg1wd2Dqit0ZJI38/B8RRtxjAJY0XCVpXwRGGdTpA2ezu5ucu2Op1yeUpHr1+dZZux7rdk+jPMR2QeM6nTEJUgVgEZY5zo/uChDrD8COFPGLGGuUJ4r4UGf/MzycOR77lJw5q8oXpUu87asVt8tSQKi4EmU5R6eImpOoUc5w/p48K9y8ywWAY+F2sYQBotgR3zgmeiOig5ekV0HizRnyTabC2tyzDR9gzkhSuEjOFUjHEUbHB97Qk2JVNw2x1F0IEzeI9O9ye9pH8+bhgWgdu8HaXb3Rm6TPWD4iRg1ZS1k5FhaV51pflBrzSMES+Zjn4ru6nNc3CxAUHJGDQXUg4gFJOODAURJBI/3oM+ykn+roj8i8H4FInTDMuOR8dzqjX0i4+0aLHvzHGiBL/b6bKXV3y4ybHjBjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
  targets:
    - [conda-forge, dev]
